[package]
name = "floating-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
floating = { path = "../floating" }
anyhow = "1.0.43"
half = "2.4.1"
num-bigint = "0.4.3"
